
//----------------------------------------------------
// The following code was generated by CUP v0.10g
// Sun Mar 09 19:46:01 CDT 2025
//----------------------------------------------------

package Parse;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  static final int SHORT = 50;
  static final int TIMES = 18;
  static final int GT = 24;
  static final int ARROW = 67;
  static final int DIVASSIGN = 66;
  static final int TYPE = 89;
  static final int CONST = 52;
  static final int GE = 25;
  static final int PERIOD = 78;
  static final int REGISTER = 40;
  static final int ENUM = 56;
  static final int RBRACK = 13;
  static final int SIZEOF = 45;
  static final int COMMA = 7;
  static final int RBRACE = 15;
  static final int RPAREN = 11;
  static final int LBRACK = 12;
  static final int LT = 22;
  static final int INCREMENT = 71;
  static final int SUBASSIGN = 68;
  static final int DOUBLE = 48;
  static final int BWISEANDASSIGN = 73;
  static final int STRUCT = 43;
  static final int LBRACE = 14;
  static final int LPAREN = 10;
  static final int MODASSIGN = 74;
  static final int TILDE = 75;
  static final int NIL = 87;
  static final int ARRAY = 84;
  static final int LE = 23;
  static final int VAR = 38;
  static final int BITWISEAND = 79;
  static final int FLOAT = 51;
  static final int THEN = 31;
  static final int GOTO = 55;
  static final int EQ = 20;
  static final int LSHIFTASSIGN = 60;
  static final int MODULUS = 80;
  static final int LONG = 54;
  static final int PLUS = 16;
  static final int DIVIDE = 19;
  static final int WHILE = 32;
  static final int UNION = 49;
  static final int ASSIGN = 28;
  static final int CHAR = 57;
  static final int ADDASSIGN = 70;
  static final int DO = 35;
  static final int FOR = 33;
  static final int VOID = 53;
  static final int EXTERN = 47;
  static final int RETURN = 46;
  static final int ELSE = 30;
  static final int BREAK = 36;
  static final int FUN = 37;
  static final int DOT = 83;
  static final int INT = 6;
  static final int EOF = 0;
  static final int SEMICOLON = 9;
  static final int MULASSIGN = 72;
  static final int ELIPSES = 61;
  static final int FUNCTION = 88;
  static final int DECREMENT = 69;
  static final int MINUS = 17;
  static final int IN = 82;
  static final int OR = 27;
  static final int error = 1;
  static final int DECIMAL_LITERAL = 4;
  static final int CONTINUE = 41;
  static final int IF = 29;
  static final int BWISEOR = 76;
  static final int ID = 2;
  static final int OF = 86;
  static final int END = 85;
  static final int COLON = 8;
  static final int BWISEXOR = 77;
  static final int BWISEORASSIGN = 62;
  static final int RSHIFTASSIGN = 59;
  static final int VOLATILE = 39;
  static final int CHAR_LITERAL = 5;
  static final int RSHIFT = 64;
  static final int STRING = 3;
  static final int BWISEXORASSIGN = 63;
  static final int NEQ = 21;
  static final int AND = 26;
  static final int TO = 34;
  static final int STATIC = 44;
  static final int LSHIFT = 65;
  static final int LET = 81;
  static final int TYPEDEF = 42;
  static final int AUTO = 58;

  /* non terminals */
  static final int Var = 2;
  static final int type = 16;
  static final int fieldVar = 8;
  static final int fieldExps = 20;
  static final int nameType = 17;
  static final int optFields = 19;
  static final int $START = 0;
  static final int empty = 22;
  static final int sequence = 6;
  static final int typeDec = 12;
  static final int subscriptVar = 9;
  static final int functionDec = 14;
  static final int optArguments = 5;
  static final int decList = 10;
  static final int dec = 11;
  static final int fields = 18;
  static final int Exp = 1;
  static final int optFunctions = 15;
  static final int optTypes = 13;
  static final int seqTail = 7;
  static final int optFieldExps = 21;
  static final int ExpList = 3;
  static final int arguments = 4;
}

